# Generated by Django 4.2.27 on 2026-02-03 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_alerta_antes', models.PositiveIntegerField(default=30, verbose_name='Dias de Alerta Antes da Validade')),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Preferências',
                'verbose_name_plural': 'Preferências',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comercial', models.CharField(max_length=200, verbose_name='Nome Comercial')),
                ('principio_activo', models.CharField(blank=True, max_length=200, verbose_name='Princípio Activo')),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=100, verbose_name='Forma Farmacêutica')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nome_comercial'],
            },
        ),
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_inicial', models.PositiveIntegerField(verbose_name='Quantidade Inicial')),
                ('quantidade_actual', models.PositiveIntegerField(verbose_name='Quantidade Actual')),
                ('unidade', models.CharField(default='unidades', max_length=50, verbose_name='Unidade')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('lote', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embalagens', to='pharmacy.medicamento', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Embalagem',
                'verbose_name_plural': 'Embalagens',
                'ordering': ['data_validade'],
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('embalagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='pharmacy.embalagem', verbose_name='Embalagem')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
