# Generated by Django 4.2.27 on 2026-02-20 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='anulado',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='anulado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Anulado em'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_anulados', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='motivo_anulacao',
            field=models.TextField(blank=True, verbose_name='Motivo da Anulação'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='utilizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to=settings.AUTH_USER_MODEL, verbose_name='Consumido por'),
        ),
        migrations.AddField(
            model_name='embalagem',
            name='eliminado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eliminado em'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='eliminado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eliminado em'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='eliminado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eliminado em'),
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Família')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('eliminado_em', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado em')),
                ('super_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='familia_gerida', to=settings.AUTH_USER_MODEL, verbose_name='Super User')),
            ],
            options={
                'verbose_name': 'Família',
                'verbose_name_plural': 'Famílias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='medicamento',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='pharmacy.familia', verbose_name='Família'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='pharmacy.familia', verbose_name='Família'),
        ),
    ]
