# Generated by Django 4.2.27 on 2026-02-21 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0004_convite'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistoActividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('medicamento_criado', 'Medicamento criado'), ('medicamento_editado', 'Medicamento editado'), ('medicamento_eliminado', 'Medicamento eliminado'), ('embalagem_criada', 'Embalagem criada'), ('embalagem_editada', 'Embalagem editada'), ('embalagem_eliminada', 'Embalagem eliminada'), ('consumo_registado', 'Consumo registado'), ('convite_gerado', 'Convite gerado'), ('convite_aceite', 'Convite aceite'), ('convite_revogado', 'Convite revogado'), ('membro_removido', 'Membro removido')], max_length=50, verbose_name='Tipo de Acção')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos_actividade', to='pharmacy.familia', verbose_name='Família')),
                ('utilizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registos_actividade', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Registo de Actividade',
                'verbose_name_plural': 'Registos de Actividade',
                'ordering': ['-criado_em'],
            },
        ),
    ]
